runtime: php82
entrypoint: serve index.html

handlers:
  # Route the PHP contact endpoint first (most specific)
  - url: /contact\.php
    script: auto
    secure: always

  # Serve static files with proper caching
  - url: /assets/(.*\.(css|js|png|jpg|jpeg|gif|svg|ico))$
    static_files: assets/\1
    upload: assets/.*\.(css|js|png|jpg|jpeg|gif|svg|ico)$
    http_headers:
      Cache-Control: public, max-age=31536000
    secure: always

  # Serve root path
  - url: /
    static_files: index.html
    upload: index\.html
    http_headers:
      Cache-Control: no-cache, max-age=0
    secure: always

  # Catch-all for HTML5 history routing (for SPA)
  - url: /.*
    static_files: index.html
    upload: index\.html
    http_headers:
      Cache-Control: no-cache, max-age=0
    secure: always

env_variables:
  # Set these in your local app.yaml or via Cloud Console as needed
  APP_NAME: "DiligentWorks"
  TO_EMAIL: "info.diligentworks@gmail.com"      # change to your address
  FROM_EMAIL: "info.diligentworks@gmail.com"    # must be a verified/allowed sender
  # SENDGRID_API_KEY: ""                 # set if using SendGrid for email
